// Generated by gencpp from file duckietown_msgs/DroneMode.msg
// DO NOT EDIT!


#ifndef DUCKIETOWN_MSGS_MESSAGE_DRONEMODE_H
#define DUCKIETOWN_MSGS_MESSAGE_DRONEMODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace duckietown_msgs
{
template <class ContainerAllocator>
struct DroneMode_
{
  typedef DroneMode_<ContainerAllocator> Type;

  DroneMode_()
    : drone_mode(0)  {
    }
  DroneMode_(const ContainerAllocator& _alloc)
    : drone_mode(0)  {
  (void)_alloc;
    }



   typedef uint8_t _drone_mode_type;
  _drone_mode_type drone_mode;



  enum {
    DRONE_MODE_DISARMED = 0u,
    DRONE_MODE_ARMED = 1u,
    DRONE_MODE_FLYING = 2u,
  };


  typedef boost::shared_ptr< ::duckietown_msgs::DroneMode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duckietown_msgs::DroneMode_<ContainerAllocator> const> ConstPtr;

}; // struct DroneMode_

typedef ::duckietown_msgs::DroneMode_<std::allocator<void> > DroneMode;

typedef boost::shared_ptr< ::duckietown_msgs::DroneMode > DroneModePtr;
typedef boost::shared_ptr< ::duckietown_msgs::DroneMode const> DroneModeConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duckietown_msgs::DroneMode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duckietown_msgs::DroneMode_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace duckietown_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'duckietown_msgs': ['/duckietown/catkin_ws/src/dt-ros-commons/packages/duckietown_msgs/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::DroneMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::DroneMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::DroneMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::DroneMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::DroneMode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::DroneMode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duckietown_msgs::DroneMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b59b67ae59d5510222e083f7dcf98328";
  }

  static const char* value(const ::duckietown_msgs::DroneMode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb59b67ae59d55102ULL;
  static const uint64_t static_value2 = 0x22e083f7dcf98328ULL;
};

template<class ContainerAllocator>
struct DataType< ::duckietown_msgs::DroneMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duckietown_msgs/DroneMode";
  }

  static const char* value(const ::duckietown_msgs::DroneMode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duckietown_msgs::DroneMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Power supply status constants\n"
"uint8 DRONE_MODE_DISARMED = 0\n"
"uint8 DRONE_MODE_ARMED = 1\n"
"uint8 DRONE_MODE_FLYING = 2\n"
"\n"
"# The drone status  as reported. Values defined above\n"
"uint8 drone_mode\n"
;
  }

  static const char* value(const ::duckietown_msgs::DroneMode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duckietown_msgs::DroneMode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.drone_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DroneMode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duckietown_msgs::DroneMode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duckietown_msgs::DroneMode_<ContainerAllocator>& v)
  {
    s << indent << "drone_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.drone_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCKIETOWN_MSGS_MESSAGE_DRONEMODE_H
